services:

  postgres:
    image: postgres:16
    hostname: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=redBooooooook
    volumes:
      - ./data:/var/lib/postgresql/data_two

